### ISSUE TITLE
Container doesn't expose ports

### ISSUE THREAD

**Issue by vertuk** [fuzzknob/dload#1]
Trying to launch your image on an arm64 machine from your example docker-compose file in Portainer. The stack gets deployed successfully, but container logs have only this string repeating:

```/init: 37: s6-overlay-suexec: Exec format error
/init: 37: s6-overlay-suexec: Exec format error
/init: 37: s6-overlay-suexec: Exec format error
/init: 37: s6-overlay-suexec: Exec format error
...
```
and so on.

My docker-compose:
```
version: "3"

services:
  dload:
    container_name: dload
    image: fuzzknob/dload@sha256:ff831a6ebbdf60bd5758efcbafe2009c09369a3cc80f9b996033087a7befc0e0
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/zhaba/download-manager/config:/config
      - /media/hddisk/downloads:/downloads
    ports:
      - 39913:80
    restart: unless-stopped
```
All binded folders exist and have according permissions and owners of PUID=1000 and PGID=1000.

When i try to use the amd64 image everything looks the same and this happens in logs:
```
exec /init: exec format error
exec /init: exec format error
exec /init: exec format error
...
```
and so on.
