### ISSUE TITLE
Files gets saved with wrong ownership

### ISSUE THREAD

**Issue by IIRobotNinjaII** [fuzzknob/dload#2]
The files get saved with a different PUID and GUID rather than what was specified in the docker compose files, which does'nt allow them to be edited in other applications such as filebrowser.

Compose File
```
version: "3"

services:
  dload:
    container_name: dload
    image: fuzzknob/dload
    environment:
      - PUID=1002
      - PGID=1002
      volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8080:80
    restart: unless-stopped
 ```
 
 Files are saved with puid 1000 instead of 1002
